### PR TITLE
Add code coverage report

### PR DESCRIPTION
**Pull request by Rafiot**
And add some more infrastructures on travis.

### CODE REVIEW

**Comment by gtback** [comment]
Hi @Rafiot ! Thanks for the pull request. I'm excited about getting this merged in. 

Are you able to sign the [contributor license agreement](https://www.oasis-open.org/resources/open-repositories/cla) per [CONTRIBUTING.md](https://github.com/oasis-open/cti-python-stix2/blob/master/CONTRIBUTING.md)? This is a sort of edge case since it's not exactly code, but it would still be great if you could.

**Comment by Rafiot** [comment]
Hey @gtback, to answer that question, Ill need our lawyer to look at it. @matthieu-farcot can you tell me, please?

**Comment by adulau** [comment]
Hi @gtback we just signed the CLA as you can see in the repository https://www.oasis-open.org/resources/open-repositories/cla/view-individual We hope this helps. Cheers.

**Comment by gtback** [comment]
Thanks, @adulau !

**Pull request merged**
