### PR TITLE
Make sure UUID in the ID is a valid UUID, and not just UUID4

### PR DESCRIPTION
**Pull request by traut**

### CODE REVIEW

**Comment by emmanvg** [comment]
Hi @traut, I think this is a good change. Though, the best option is to leave this PR on hold until the next STIX CSD gets approved. This way we can start updating the library systematically to match the new CSD as we have done up to now. While that happens could you update the tests for this PR?

**Comment by emmanvg** [comment]
One more thing @traut. Can you please sign the [individual](https://www.oasis-open.org/resources/open-repositories/cla/individual-cla) CLA for OASIS?

**Comment by traut** [comment]
@emmanvg done, just signed it.

**Comment by traut** [comment]
for some reason `add-trailing-comma` task is failing during build. @emmanvg any ideas how to fix that?

**Comment by traut** [comment]
❤️

**Comment by traut** [comment]
can this be merged?

**Comment by clenk** [comment]
Hi @traut, thanks for the PR. However, I think we want to keep the old functionality for 2.0 and just relax the UUID requirements for 2.1. We're hoping to have some code up to do this soon.

**Comment by clenk** [comment]
These changes have been implemented in the [stix2.1 branch](https://github.com/oasis-open/cti-python-stix2/tree/stix2.1). Thanks for the PR, @traut!

**Pull request closed without merging**
