### PR TITLE
Make Mutex 'name' required. Bunch of formatting changes, add test for custom extension

### PR DESCRIPTION
**Pull request by emmanvg**
Related to #68

### CODE REVIEW

**Comment by clenk** [comment]
Looks nice! Should we also check that the custom extension's `properties` arg is not an empty dict (`{}`) in addition to checking that it's not `None`?

**Comment by emmanvg** [comment]
That's right, we should also check is not empty. Good catch!

**Comment by emmanvg** [comment]
Could you add it, as part of merging with master?

**Comment by clenk** [comment]
Will do.

**Pull request merged**
