### PR TITLE
Better coverage for TAXIICollections

### PR DESCRIPTION
**Pull request by emmanvg**
This request contains the following changes:

- Increased coverage for TAXII datastores.
- Separated each datastore type tests into its own file. It is better to read and also easier to track errors or add more tests.
- Created a MockTAXIIClient that uses components from `taxii2client` and `medallion` to mimic the behavior of both libraries.
- Updated the `taxii_example.py` file to reflect recent changes made to the libraries.

Related #148 and #169

### CODE REVIEW

**Comment by gtback** [comment]
I'd like @clenk or @mbastian1135 to take a look as well before merging.

**Comment by mbastian1135** [comment]
@gtback - Ill take a look as soon as I can. I was chatting with Emmanuelle too while he was doing this (bc he was fixing my errors) so familiar with it.

**Comment by emmanvg** [comment]
Updated the DataStore API documentation to reflect the proper TAXII2 filter fields. Thanks @clenk

**Comment by emmanvg** [comment]
There was also an operator that was not being displayed. I added the ``` and hopefully have the same behavior as `>=`

**Comment by clenk** [comment]
Looks good; thank you @emmanvg!

**Pull request merged**
