### PR TITLE
Add swid property to the software SCO

### LINKED ISSUE #349: Changes made to Software SCO, and its usage.
See https://github.com/oasis-tcs/cti-stix2/issues/220

### PR DESCRIPTION
**Pull request by chisholm**
Fixes #349

### CODE REVIEW

**Comment by clenk** [comment]
I think the format of swid tags is more like `org.fedoraproject.Fedora-29`. Should we update the test example? I don't know the swid tag for MS Word, though.

**Comment by rpiazza** [comment]
@clenk, @chisholm  - looked at examples in https://nvlpubs.nist.gov/nistpubs/ir/2016/NIST.IR.8060.pdf

Here is a good one: 
tagId="com.acme.rms-ce-v4-1-5-0".

Maybe change the cpe one to correspond to this?

**Comment by chisholm** [comment]
I was looking for info about tagIds too when I was developing this.  I don't remember where I saw it, but I remember reading that they aren't required to be any particular thing.  There may be some "should" rules around them though.  So a UUID seemed good enough, and not technically wrong.  But I'll change the test.

**Comment by rpiazza** [comment]
Yes - I agree - its not defined very well.  It took the text for the STIX spec directly from the document I referred to above.

**Comment by clenk** [comment]
Thanks @chisholm!

**Pull request merged**
