### PR TITLE
Fix bug when adding custom object to FileSystemSink if the object type hasn't been registered

### PR DESCRIPTION
**Pull request by clenk**
Related: #429.

### CODE REVIEW

**Comment by emmanvg** [comment]
General comment for this PR is that serialization logic being removed from `_STIXBase` and being standalone it can follow a similar path to the `versioning.py` or `parsing.py` modules. Perhaps we could move the `serialize`, `STIXJSONEncoder` and the `STIXJSONIncludeOptionalDefaultsEncoder` to their own separate module.

This would also remove the `__all__` override under `base.py`

**Comment by chisholm** [comment]
While you're at it... what about the `find_property_index()` stuff from utils?  It's only used for pretty-serialization.  Maybe it belongs in serialization.py too.

**Comment by emmanvg** [comment]
Agree @chisholm, will make the change

**Comment by clenk** [comment]
These changes look good to me!

**Pull request merged**
